import { InterviewCategory, ProgrammingLanguage, Topic } from './types';

export const categoryLabels: Record<InterviewCategory, string> = {
  'programming-languages': 'Programming Languages',
  dsa: 'Data Structures & Algorithms',
  'machine-learning': 'Machine Learning',
  'operating-systems': 'Operating Systems',
  dbms: 'Database Management System',
  'computer-networks': 'Computer Networks',
  algorithms: 'Algorithms',
  aptitude: 'Aptitude',
  hr: 'HR Interview',
};

export const categoryIcons: Record<InterviewCategory, string> = {
  'programming-languages': 'Code2',
  dsa: 'GitBranch',
  'machine-learning': 'Brain',
  'operating-systems': 'Monitor',
  dbms: 'Database',
  'computer-networks': 'Globe',
  algorithms: 'Sigma',
  aptitude: 'Calculator',
  hr: 'Users',
};

export const programmingLanguages: { id: ProgrammingLanguage; label: string; icon: string }[] = [
  { id: 'java', label: 'Java', icon: '☕' },
  { id: 'python', label: 'Python', icon: '🐍' },
  { id: 'javascript', label: 'JavaScript', icon: '🟨' },
  { id: 'typescript', label: 'TypeScript', icon: '🔷' },
  { id: 'c', label: 'C', icon: '⚙️' },
  { id: 'cpp', label: 'C++', icon: '⚡' },
  { id: 'go', label: 'Go', icon: '🐹' },
  { id: 'rust', label: 'Rust', icon: '🦀' },
  { id: 'kotlin', label: 'Kotlin', icon: '🅺' },
  { id: 'swift', label: 'Swift', icon: '🐦' },
  { id: 'dart', label: 'Dart', icon: '🎯' },
];

export const categoryTopics: Record<InterviewCategory, Topic[]> = {
  'programming-languages': [],
  dsa: [
    { id: 'arrays', label: 'Arrays' },
    { id: 'strings', label: 'Strings' },
    { id: 'linked-lists', label: 'Linked Lists' },
    { id: 'stacks-queues', label: 'Stacks & Queues' },
    { id: 'trees', label: 'Trees' },
    { id: 'graphs', label: 'Graphs' },
    { id: 'hash-tables', label: 'Hash Tables' },
    { id: 'heaps', label: 'Heaps' },
    { id: 'tries', label: 'Tries' },
    { id: 'recursion', label: 'Recursion' },
    { id: 'sorting', label: 'Sorting' },
    { id: 'searching', label: 'Searching' },
  ],
  'machine-learning': [
    { id: 'supervised-learning', label: 'Supervised Learning' },
    { id: 'unsupervised-learning', label: 'Unsupervised Learning' },
    { id: 'deep-learning', label: 'Deep Learning' },
    { id: 'neural-networks', label: 'Neural Networks' },
    { id: 'cnn', label: 'CNNs' },
    { id: 'rnn-lstm', label: 'RNNs & LSTMs' },
    { id: 'transformers', label: 'Transformers' },
    { id: 'reinforcement-learning', label: 'Reinforcement Learning' },
    { id: 'feature-engineering', label: 'Feature Engineering' },
    { id: 'model-evaluation', label: 'Model Evaluation' },
    { id: 'nlp', label: 'NLP' },
    { id: 'computer-vision', label: 'Computer Vision' },
  ],
  'operating-systems': [
    { id: 'process-management', label: 'Process Management' },
    { id: 'memory-management', label: 'Memory Management' },
    { id: 'file-systems', label: 'File Systems' },
    { id: 'scheduling', label: 'CPU Scheduling' },
    { id: 'synchronization', label: 'Synchronization' },
    { id: 'deadlocks', label: 'Deadlocks' },
    { id: 'virtual-memory', label: 'Virtual Memory' },
    { id: 'io-management', label: 'I/O Management' },
    { id: 'security', label: 'Security' },
  ],
  dbms: [
    { id: 'relational-model', label: 'Relational Model' },
    { id: 'sql', label: 'SQL' },
    { id: 'normalization', label: 'Normalization' },
    { id: 'transactions', label: 'Transactions' },
    { id: 'indexing', label: 'Indexing' },
    { id: 'query-optimization', label: 'Query Optimization' },
    { id: 'nosql', label: 'NoSQL Databases' },
    { id: 'acid-properties', label: 'ACID Properties' },
    { id: 'concurrency-control', label: 'Concurrency Control' },
    { id: 'er-diagrams', label: 'ER Diagrams' },
  ],
  'computer-networks': [
    { id: 'osi-model', label: 'OSI Model' },
    { id: 'tcp-ip', label: 'TCP/IP' },
    { id: 'http-https', label: 'HTTP/HTTPS' },
    { id: 'dns', label: 'DNS' },
    { id: 'routing', label: 'Routing Protocols' },
    { id: 'security', label: 'Network Security' },
    { id: 'sockets', label: 'Sockets' },
    { id: 'ip-addressing', label: 'IP Addressing' },
    { id: 'load-balancing', label: 'Load Balancing' },
    { id: 'cdn', label: 'CDN' },
  ],
  algorithms: [
    { id: 'searching', label: 'Searching Algorithms' },
    { id: 'sorting', label: 'Sorting Algorithms' },
    { id: 'divide-conquer', label: 'Divide & Conquer' },
    { id: 'greedy', label: 'Greedy Algorithms' },
    { id: 'dynamic-programming', label: 'Dynamic Programming' },
    { id: 'backtracking', label: 'Backtracking' },
    { id: 'graph-algorithms', label: 'Graph Algorithms' },
    { id: 'string-algorithms', label: 'String Algorithms' },
    { id: 'bit-manipulation', label: 'Bit Manipulation' },
    { id: 'pattern-matching', label: 'Pattern Matching' },
  ],
  aptitude: [
    { id: 'quantitative', label: 'Quantitative Aptitude' },
    { id: 'logical-reasoning', label: 'Logical Reasoning' },
    { id: 'verbal-ability', label: 'Verbal Ability' },
    { id: 'data-interpretation', label: 'Data Interpretation' },
    { id: 'probability', label: 'Probability' },
    { id: 'permutations-combinations', label: 'Permutations & Combinations' },
  ],
  hr: [
    { id: 'introduction', label: 'Self Introduction' },
    { id: 'experience', label: 'Experience & Projects' },
    { id: 'strengths-weaknesses', label: 'Strengths & Weaknesses' },
    { id: 'career-goals', label: 'Career Goals' },
    { id: 'teamwork', label: 'Teamwork & Collaboration' },
    { id: 'conflict-resolution', label: 'Conflict Resolution' },
    { id: 'leadership', label: 'Leadership' },
    { id: 'why-company', label: 'Why This Company' },
  ],
};

export const languageTopics: Record<ProgrammingLanguage, Topic[]> = {
  java: [
    { id: 'java-basics', label: 'Basics & Syntax' },
    { id: 'oop', label: 'Object Oriented Programming' },
    { id: 'collections', label: 'Collections Framework' },
    { id: 'exceptions', label: 'Exception Handling' },
    { id: 'multithreading', label: 'Multithreading' },
    { id: 'generics', label: 'Generics' },
    { id: 'lambda-streams', label: 'Lambda & Streams' },
    { id: 'io', label: 'I/O & File Handling' },
    { id: 'jdbc', label: 'JDBC & Databases' },
    { id: 'spring', label: 'Spring Framework' },
    { id: 'hibernate', label: 'Hibernate' },
    { id: 'microservices', label: 'Microservices' },
  ],
  python: [
    { id: 'py-basics', label: 'Variables & Data Types' },
    { id: 'py-operators', label: 'Operators' },
    { id: 'py-loops', label: 'Loops' },
    { id: 'py-functions', label: 'Functions' },
    { id: 'py-oop', label: 'Object Oriented Programming' },
    { id: 'py-collections', label: 'Collections' },
    { id: 'py-exceptions', label: 'Exception Handling' },
    { id: 'py-files', label: 'File Handling' },
    { id: 'py-decorators', label: 'Decorators' },
    { id: 'py-generators', label: 'Generators' },
    { id: 'py-iterators', label: 'Iterators' },
    { id: 'py-async', label: 'Async Programming' },
    { id: 'py-threading', label: 'Multithreading' },
    { id: 'py-apis', label: 'APIs & REST' },
    { id: 'py-flask', label: 'Flask' },
    { id: 'py-django', label: 'Django' },
  ],
  javascript: [
    { id: 'js-basics', label: 'Basics & Syntax' },
    { id: 'js-functions', label: 'Functions & Scope' },
    { id: 'js-objects', label: 'Objects & Prototypes' },
    { id: 'js-async', label: 'Async Programming' },
    { id: 'js-promises', label: 'Promises & Callbacks' },
    { id: 'js-closures', label: 'Closures' },
    { id: 'js-dom', label: 'DOM Manipulation' },
    { id: 'js-es6', label: 'ES6+ Features' },
    { id: 'js-modules', label: 'Modules' },
    { id: 'js-error-handling', label: 'Error Handling' },
    { id: 'react', label: 'React' },
    { id: 'nodejs', label: 'Node.js' },
  ],
  typescript: [
    { id: 'ts-basics', label: 'Basic Types' },
    { id: 'ts-interfaces', label: 'Interfaces' },
    { id: 'ts-types', label: 'Advanced Types' },
    { id: 'ts-generics', label: 'Generics' },
    { id: 'ts-decorators', label: 'Decorators' },
    { id: 'ts-classes', label: 'Classes & Inheritance' },
    { id: 'ts-modules', label: 'Modules' },
    { id: 'ts-utility-types', label: 'Utility Types' },
    { id: 'ts-type-guards', label: 'Type Guards' },
    { id: 'ts-config', label: 'Configuration' },
  ],
  c: [
    { id: 'c-basics', label: 'Basics & Syntax' },
    { id: 'c-pointers', label: 'Pointers' },
    { id: 'c-memory', label: 'Memory Management' },
    { id: 'c-structures', label: 'Structures & Unions' },
    { id: 'c-functions', label: 'Functions' },
    { id: 'c-file-io', label: 'File I/O' },
    { id: 'c-preprocessor', label: 'Preprocessor Directives' },
    { id: 'c-dynamic-memory', label: 'Dynamic Memory Allocation' },
  ],
  cpp: [
    { id: 'cpp-basics', label: 'Basics & Syntax' },
    { id: 'cpp-oop', label: 'Object Oriented Programming' },
    { id: 'cpp-stl', label: 'STL Containers' },
    { id: 'cpp-templates', label: 'Templates' },
    { id: 'cpp-pointers', label: 'Pointers & References' },
    { id: 'cpp-memory', label: 'Memory Management' },
    { id: 'cpp-exceptions', label: 'Exception Handling' },
    { id: 'cpp-multithreading', label: 'Multithreading' },
    { id: 'cpp-smart-pointers', label: 'Smart Pointers' },
    { id: 'cpp-move-semantics', label: 'Move Semantics' },
  ],
  go: [
    { id: 'go-basics', label: 'Basics & Syntax' },
    { id: 'go-concurrency', label: 'Concurrency' },
    { id: 'go-goroutines', label: 'Goroutines' },
    { id: 'go-channels', label: 'Channels' },
    { id: 'go-interfaces', label: 'Interfaces' },
    { id: 'go-structs', label: 'Structs & Methods' },
    { id: 'go-error-handling', label: 'Error Handling' },
    { id: 'go-packages', label: 'Packages & Modules' },
    { id: 'go-testing', label: 'Testing' },
  ],
  rust: [
    { id: 'rust-basics', label: 'Basics & Syntax' },
    { id: 'rust-ownership', label: 'Ownership & Borrowing' },
    { id: 'rust-lifetimes', label: 'Lifetimes' },
    { id: 'rust-traits', label: 'Traits & Generics' },
    { id: 'rust-enums', label: 'Enums & Pattern Matching' },
    { id: 'rust-error', label: 'Error Handling' },
    { id: 'rust-concurrency', label: 'Concurrency' },
    { id: 'rust-unsafe', label: 'Unsafe Rust' },
    { id: 'rust-macros', label: 'Macros' },
  ],
  kotlin: [
    { id: 'kt-basics', label: 'Basics & Syntax' },
    { id: 'kt-null-safety', label: 'Null Safety' },
    { id: 'kt-functions', label: 'Functions & Lambdas' },
    { id: 'kt-classes', label: 'Classes & Objects' },
    { id: 'kt-coroutines', label: 'Coroutines' },
    { id: 'kt-collections', label: 'Collections' },
    { id: 'kt-extensions', label: 'Extension Functions' },
    { id: 'kt-flow', label: 'Flow & RxJava' },
    { id: 'kt-compose', label: 'Jetpack Compose' },
  ],
  swift: [
    { id: 'sw-basics', label: 'Basics & Syntax' },
    { id: 'sw-optionals', label: 'Optionals' },
    { id: 'sw-structs-classes', label: 'Structs & Classes' },
    { id: 'sw-protocols', label: 'Protocols & Extensions' },
    { id: 'sw-closures', label: 'Closures' },
    { id: 'sw-generics', label: 'Generics' },
    { id: 'sw-error-handling', label: 'Error Handling' },
    { id: 'sw-concurrency', label: 'Concurrency & Async/Await' },
    { id: 'sw-swiftui', label: 'SwiftUI' },
    { id: 'sw-combine', label: 'Combine Framework' },
  ],
  dart: [
    { id: 'dart-basics', label: 'Basics & Syntax' },
    { id: 'dart-oop', label: 'Object Oriented Programming' },
    { id: 'dart-collections', label: 'Collections' },
    { id: 'dart-async', label: 'Async Programming' },
    { id: 'dart-streams', label: 'Streams' },
    { id: 'dart-error', label: 'Error Handling' },
    { id: 'dart-generics', label: 'Generics' },
    { id: 'dart-flutter-widgets', label: 'Flutter Widgets' },
    { id: 'dart-state-management', label: 'State Management' },
  ],
};
